name: CV_Site CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CV_Site

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './CV_Site/package-lock.json'
      - run: npm ci
      - run: npm run build --if-present
